
package br.gov.saude.servicos.sigtap.v1.procedimentoservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-18T11:58:00.851-03:00
 * Generated source version: 3.3.5
 *
 */
public final class ProcedimentoServicePortType_ProcedimentoServiceSOAP11Port_Client {

    private static final QName SERVICE_NAME = new QName("http://servicos.saude.gov.br/sigtap/v1/procedimentoservice", "ProcedimentoService");

    private ProcedimentoServicePortType_ProcedimentoServiceSOAP11Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProcedimentoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ProcedimentoService ss = new ProcedimentoService(wsdlURL, SERVICE_NAME);
        ProcedimentoServicePortType port = ss.getProcedimentoServiceSOAP11Port();

        {
        System.out.println("Invoking pesquisarProcedimentos...");
        br.gov.saude.servicos.sigtap.v1.procedimentoservice.RequestPesquisarProcedimentos _pesquisarProcedimentos_requestPesquisarProcedimentos = null;
        try {
            br.gov.saude.servicos.sigtap.v1.procedimentoservice.ResponsePesquisarProcedimentos _pesquisarProcedimentos__return = port.pesquisarProcedimentos(_pesquisarProcedimentos_requestPesquisarProcedimentos);
            System.out.println("pesquisarProcedimentos.result=" + _pesquisarProcedimentos__return);

        } catch (SIGTAPFault e) {
            System.out.println("Expected exception: SIGTAPFault has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking detalharProcedimento...");
        br.gov.saude.servicos.sigtap.v1.procedimentoservice.RequestDetalharProcedimento _detalharProcedimento_requestDetalharProcedimento = null;
        try {
            br.gov.saude.servicos.sigtap.v1.procedimentoservice.ResponseDetalharProcedimento _detalharProcedimento__return = port.detalharProcedimento(_detalharProcedimento_requestDetalharProcedimento);
            System.out.println("detalharProcedimento.result=" + _detalharProcedimento__return);

        } catch (SIGTAPFault e) {
            System.out.println("Expected exception: SIGTAPFault has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
